### ISSUE TITLE
ModuleNotFoundError: No module named 'sortedness.wtau.wtau'

### ISSUE THREAD

**Issue by Bachery** [sortedness/sortedness#1]
Hi, I install from PyPI and it reports this module missing error when I import the package

**Comment by davips** [comment]
It works for me on a fresh install, can you show me the code where it fails ?

**Comment by Bachery** [comment]
I just create a new enviroment via conda:
```
conda create -n p11 python=3.11
conda activate p11
pip install numpy scipy
pip install -U sortedness
python
```
and import the pakage `from sortedness import sortedness`, it reports:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/p11/lib/python3.11/site-packages/sortedness/__init__.py", line 2, in <module>
    from sortedness.local import pwsortedness, sortedness, rsortedness
  File "/usr/local/anaconda3/envs/p11/lib/python3.11/site-packages/sortedness/local.py", line 36, in <module>
    from sortedness.wtau import parwtau
  File "/usr/local/anaconda3/envs/p11/lib/python3.11/site-packages/sortedness/wtau/__init__.py", line 37, in <module>
    from .wtau import _weightedrankedtau  # Source wtau.pyx becomes wtau.c and shared so
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'sortedness.wtau.wtau'
```

**Comment by davips** [comment]
Please see if it works now with v0.230706.3: 
`pip uninstall sortedness`
`pip install -U sortedness`

pwsortedness probably still wont work on `conda`, only `venv`, but it is the slowest ~~and less useful~~ of all measures in the package. Cython code inside pwsortedness can be replaced in the future by pure python for compatibility (and more slowness).

**Comment by Bachery** [comment]
Thanks, it works now. And as you said, only `pwsortedness` doesn't work yet.

**Comment by davips** [comment]
Now pwsortedness has an option to disable cython. It is actually more useful than the others for single point projection assessment: 
https://github.com/sortedness/sortedness/releases/tag/v0.230710.0
